services:
  pandadawrazor:
    image: pandadawrazor
    build:
      context: .
      dockerfile: PandaDawRazor/Dockerfile

  pandaback:
    image: pandaback
    build:
      context: .
      dockerfile: PandaBack/Dockerfile

